databases:
    name: django_construct-app
    databaseName: constructdb
    user: mysite

services:
  - type: web
    name: django_construct-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn construct_youtube.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_construct-app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4