# Generated by Django 4.1.4 on 2022-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nome',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AddField(
            model_name='users',
            name='senha',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='sobrenome',
            field=models.CharField(default=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
